### ISSUE TITLE
Linkedin login page clone

### ISSUE THREAD

**Issue by omkar787** [omkar787/SoPhish#2]
Linkedin phishing page creation

**Comment by ssurbhi09** [comment]
Can I make Google clone?

**Comment by ParamTatiya02** [comment]
I would like to perform this task. could you assign it to me?

**Comment by omkar787** [comment]
@ParamTatiya02 Ok, I am assigning this issue to you.

**Comment by prachi0117** [comment]
i want to contribute to this. Could you assign to me?

**Comment by omkar787** [comment]
Hello @prachi0117,
Note: @ParamTatiya02 is already working on this, do you want to work together?

**Comment by prachi0117** [comment]
> Hello @prachi0117, Note: @ParamTatiya02 is already working on this, do you want to work together?

I am already done with the html part and soon  I will complete with the css one. So if you could assign it to me?

**Comment by omkar787** [comment]
#18 Improved this LinkedIn login page. Tried to replicate the original
