### ISSUE TITLE
Facebook login page

### ISSUE THREAD

**Issue by omkar787** [omkar787/SoPhish#3]
Facebook page creation

**Comment by ssurbhi09** [comment]
Can I make Google clone website if yes then please assign me!

**Comment by omkar787** [comment]
#5 Basic designing of Facebook login page done.

**Comment by ParamTatiya02** [comment]
Can you assign this task to me?

**Comment by omkar787** [comment]
We have a Facebook clone, if you want to improve it, I can assign it to you.
And You already have #2 assigned, do you want this too?

**Comment by ParamTatiya02** [comment]
okk no problem .i will just do the linkedin one
