### ISSUE TITLE
Twitter page clone

### ISSUE THREAD

**Issue by omkar787** [omkar787/SoPhish#7]
Creation of Twitter clone. Login or registration clone.

**Comment by sunidhisachan** [comment]
@omkar787 I can try this

**Comment by omkar787** [comment]
Hello @sunidhisachan. I have assigned it to you

**Comment by omkar787** [comment]
@pushpanjali-10 Yeah, you can create a sub folder in the twitter folder and work there.

**Comment by pushpanjali-10** [comment]
Done
